@url = http://localhost:3000/rating

### Get All Ratings
GET {{url}}


### Get Single Ratings
GET {{url}}/61b77c34bb7968b1c861e5aa


### Create Rating
POST {{url}}
Content-Type: application/json

{
    "productId": 5678,
    "userId": 5678,
    "score": 5,
    "message": "Ótimo"
}


### Update Rating
PUT {{url}}/61b77c34bb7968b1c861e5aa
Content-Type: application/json

{
    "score": 5
}


### Remove Rating
DELETE {{url}}/61b77c34bb7968b1c861e5aa
