@url = http://localhost:3002/ratings

### Get All Ratings
GET {{url}}


### Get Single Ratings
GET {{url}}/1


### Get Rating by productId
GET {{url}}/products/1


### Create Rating
POST {{url}}
Content-Type: application/json

{
    "productId": 1,
    "userId": 2,
    "score": 5,
    "message": "Show de bola!"
}


### Update Rating
PUT {{url}}/1
Content-Type: application/json

{
    "message": "Muito bom"
}


### Remove Rating
DELETE {{url}}/1
