@base = http://localhost:3000/products
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlzX2FkbWluIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDIxLTEyLTEwVDIxOjU1OjM2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEyLTEwVDIxOjU1OjM2LjAwMFoifSwibG9nZ2VkSW4iOiIyMDIxLTEyLTExVDAwOjM3OjM3LjQzMFoiLCJleHBpcmVzSW4iOiIyMDIxLTEyLTEyVDAwOjM3OjM3LjQzMFoiLCJpYXQiOjE2MzkxODMwNTcsImV4cCI6MTYzOTI2OTQ1N30.xG_XL7dDAL8Yvmmh1L0aP5Lq_MteTrekGXdm7fFu9dw
@non_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJuYW1lIjoiYWFhYSIsImVtYWlsIjoiYWFhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlzX2FkbWluIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMS0xMi0xMVQwMDo0ODozNi4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMi0xMVQwMDo0ODozNi4wMDBaIn0sImxvZ2dlZEluIjoiMjAyMS0xMi0xMVQwMDo0OTowMS4yMjRaIiwiZXhwaXJlc0luIjoiMjAyMS0xMi0xMlQwMDo0OTowMS4yMjRaIiwiaWF0IjoxNjM5MTgzNzQxLCJleHAiOjE2MzkyNzAxNDF9.vZd0IfljVDHTVXagvJ8n7pDOpw6q5OIdnjpd9W30L-s

### Create Product
POST {{base}}
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Carro",
    "cost": 20000.65
}

### List all Products
GET {{base}}

### Show Product
GET {{base}}/1

### Update Product
PUT {{base}}/2
Authorization: {{token}}
Content-Type: application/json

{
    "name": "TV"
}

### Delete Product
DELETE {{base}}/2
Authorization: {{token}}