@base = http://localhost:3000/orders
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlzX2FkbWluIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDIxLTEyLTEwVDIxOjU1OjM2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEyLTEwVDIxOjU1OjM2LjAwMFoifSwibG9nZ2VkSW4iOiIyMDIxLTEyLTEzVDE2OjEwOjM4LjMwM1oiLCJleHBpcmVzSW4iOiIyMDIxLTEyLTE0VDE2OjEwOjM4LjMwM1oiLCJpYXQiOjE2Mzk0MTE4MzgsImV4cCI6MTYzOTQ5ODIzOH0.6ahUnuKl_udo4U7gzdNhU3b_bsnychwxsEomd0MC7cs
@non_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJNaWNoZWwiLCJlbWFpbCI6Im1pY2hlbDVAZ21haWwuY29tIn0sImxvZ2dlZEluIjoiMjAyMS0xMi0xNFQxOToxMjoxMC44NzdaIiwiZXhwaXJlc0luIjoiMjAyMS0xMi0xNVQxOToxMjoxMC44NzdaIiwiaWF0IjoxNjM5NTA5MTMwLCJleHAiOjE2Mzk1OTU1MzB9.TUIfr0xtWAL066yepp8IY9IV-da-xtUPfVZfN0b-XEA

### List all Order
GET {{base}}
Authorization: {{non_admin}}


### Find Order
GET {{base}}/1
Authorization: {{token}}