@base = http://localhost:3000/products
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlzX2FkbWluIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDIxLTEyLTEwVDIxOjU1OjM2LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEyLTEwVDIxOjU1OjM2LjAwMFoifSwibG9nZ2VkSW4iOiIyMDIxLTEyLTEzVDE2OjEwOjM4LjMwM1oiLCJleHBpcmVzSW4iOiIyMDIxLTEyLTE0VDE2OjEwOjM4LjMwM1oiLCJpYXQiOjE2Mzk0MTE4MzgsImV4cCI6MTYzOTQ5ODIzOH0.6ahUnuKl_udo4U7gzdNhU3b_bsnychwxsEomd0MC7cs
@non_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJuYW1lIjoiYWFhYSIsImVtYWlsIjoiYWFhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlzX2FkbWluIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMS0xMi0xMVQwMDo0ODozNi4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMi0xMVQwMDo0ODozNi4wMDBaIn0sImxvZ2dlZEluIjoiMjAyMS0xMi0xM1QxNjowOTowOS45MDdaIiwiZXhwaXJlc0luIjoiMjAyMS0xMi0xNFQxNjowOTowOS45MDdaIiwiaWF0IjoxNjM5NDExNzQ5LCJleHAiOjE2Mzk0OTgxNDl9.MiIJVbnngxz5aRGvvDhRC3svxBWWBNmzND2tI2ibzGY

### Create Product
POST {{base}}
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Carro",
    "cost": 20000.65
}

### List all Products
GET {{base}}
Authorization: {{token}}

### Show Product
GET {{base}}/1
Authorization: {{token}}

### Update Product
PUT {{base}}/2
Authorization: {{token}}
Content-Type: application/json

{
    "name": "TV"
}

### Delete Product
DELETE {{base}}/2
Authorization: {{token}}