@base = http://localhost:3000/products
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlzX2FkbWluIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDIxLTEyLTE0VDAyOjI2OjMwLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEyLTE0VDAyOjI2OjMwLjAwMFoifSwibG9nZ2VkSW4iOiIyMDIxLTEyLTE0VDE3OjEwOjQwLjg1MloiLCJleHBpcmVzSW4iOiIyMDIxLTEyLTE1VDE3OjEwOjQwLjg1MloiLCJpYXQiOjE2Mzk1MDE4NDAsImV4cCI6MTYzOTU4ODI0MH0.rlFZ-pY8XsC0mEEuDCO-Dz2O3IiT6ePvWgPEJAioOqk
@non_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoidXNlciIsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQiLCJpc19hZG1pbiI6ZmFsc2UsImNyZWF0ZWRBdCI6IjIwMjEtMTItMTRUMDI6MjY6NDUuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMTItMTRUMDI6MjY6NDUuMDAwWiJ9LCJsb2dnZWRJbiI6IjIwMjEtMTItMTRUMTY6NTk6MzQuNDQ5WiIsImV4cGlyZXNJbiI6IjIwMjEtMTItMTVUMTY6NTk6MzQuNDQ5WiIsImlhdCI6MTYzOTUwMTE3NCwiZXhwIjoxNjM5NTg3NTc0fQ.qiRbb7e02RMWZznetCkZokj16L2XCQshbUaZ_LzhDgM

### Create Product
POST {{base}}
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Carro",
    "cost": 20000.65
}

### List all Products
GET {{base}}
Authorization: {{token}}

### Show Product
GET {{base}}/1
Authorization: {{token}}

### Update Product
PUT {{base}}/2
Authorization: {{token}}
Content-Type: application/json

{
    "name": "TV"
}

### Delete Product
DELETE {{base}}/2
Authorization: {{token}}