@base=http://localhost:3000/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlzX2FkbWluIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDIxLTEyLTE0VDAyOjI2OjMwLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEyLTE0VDAyOjI2OjMwLjAwMFoifSwibG9nZ2VkSW4iOiIyMDIxLTEyLTE0VDE3OjEwOjQwLjg1MloiLCJleHBpcmVzSW4iOiIyMDIxLTEyLTE1VDE3OjEwOjQwLjg1MloiLCJpYXQiOjE2Mzk1MDE4NDAsImV4cCI6MTYzOTU4ODI0MH0.rlFZ-pY8XsC0mEEuDCO-Dz2O3IiT6ePvWgPEJAioOqk
@non_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoidXNlciIsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQiLCJpc19hZG1pbiI6ZmFsc2UsImNyZWF0ZWRBdCI6IjIwMjEtMTItMTRUMDI6MjY6NDUuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMTItMTRUMDI6MjY6NDUuMDAwWiJ9LCJsb2dnZWRJbiI6IjIwMjEtMTItMTRUMDI6Mjg6MDguNzY4WiIsImV4cGlyZXNJbiI6IjIwMjEtMTItMTVUMDI6Mjg6MDguNzY4WiIsImlhdCI6MTYzOTQ0ODg4OCwiZXhwIjoxNjM5NTM1Mjg4fQ.nzBpovfe4E_JME1pibFgKSGMb2-W3Z1u4oDctF_n2T4

### Listing users
GET {{base}} HTTP/1.1
Authorization: {{token}}

### Show user
GET {{base}}/4 HTTP/1.1
Authorization: {{non_admin}}

### Creating user
POST {{base}} HTTP/1.1
Content-Type: application/json

{
    "name": "user",
    "password": "1234",
    "email": "user@gmail.com",
    "is_admin": false
}

### Updating user
PUT {{base}}/9 HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "name": "bububub",
    "email": "aa@gmail.com"
}

### Deleting user
DELETE {{base}}/9 HTTP/1.1
Authorization: {{token}}

### Login user
POST {{base}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "aaa@gmail.com",
    "password": "1234"
}